### PR TITLE
Updated the date filter 'date_from' and 'date_to'

### PR DESCRIPTION
**Pull request by aeldamaty**

### CODE REVIEW

**Comment by aeldamaty** [comment]
@funkaoshi Can you take a look at this?

**Comment by funkaoshi** [comment]
I'd add a preamble somewhere explaining that you need to tack on an "Z" if you want to filter using UTC, otherwise we assume you are filtering using your local time.

**Comment by RouganStriker** [comment]
I think that is kind of implied by the ISO standard format but we could make it more verbose for clarity

**Comment by aeldamaty** [comment]
@funkaoshi how does this look?

**Comment by funkaoshi** [comment]
This is fine, but we might want a section at the top of our docs that just talks about date filtering so you don't have to repeat yourself so much in the docs.

**Pull request merged**
