### PR TITLE
Color and brand things

### PR DESCRIPTION
**Pull request by hhaidar**

### CODE REVIEW

**Comment by funkaoshi** [comment]
you sexy bastard.

**Comment by sibartlett** [comment]
I moved this changes to the bottom of the sass files: 43b40b0c90e215b2c05b44ee435bce18cf602265

This will make it easier to merge updates from upstream.

**Comment by hhaidar** [comment]
how about a separate file altogether?

**Comment by sibartlett** [comment]
@hhaidar could do! I was just doing the easiest/straight-forward thing for now.

**Pull request merged**
