### PR TITLE
Remove active from payload

### PR DESCRIPTION
**Pull request by harry-kim**
Remove persist_open_tasks from payload and response

Refs #SDE-3641

TODO:
- [x] Set milestone label in pull request (SDE version)
- [x] Updated changelog.md
- [x] Completed documentation for the new endpoint.
- [x] Feature has been merged into SDE develop.

### CODE REVIEW

**Comment by sibartlett** [comment]
+1

**Comment by sibartlett** [comment]
Do you need to update tables, like the other pull request?

**Comment by harry-kim** [comment]
no its not in the table @sibartlett

**Comment by sibartlett** [comment]
+1

**Pull request merged**
