### PR TITLE
Document absolute_urls and to_html for Glossary terms 

### PR DESCRIPTION
**Pull request by shawngustaw**
TODO:
- [ ] Set milestone label in pull request (SDE version)
- [ ] Updated changelog.md
- [ ] Completed documentation for the new endpoint.
- [ ] Feature has been merged into SDE develop.

### CODE REVIEW

**Comment by RouganStriker** [comment]
Can we merge this into master instead?

**Comment by shawngustaw** [comment]
@RouganStriker the problem is this stuff was merged way long ago and Simon mentioned it was gonna be hacky to update things from version 3.4 -> now so it hasn't gotten done :\

**Comment by RouganStriker** [comment]
Mahima finished migrating all the slate docs over to gitbook; I want to get all these pending PRs merged in so we can do 1 final pass and migrate any remaining changes over.

**Comment by shawngustaw** [comment]
If that's the case then merge away!

**Pull request merged**
