### PR TITLE
Use guard to watch, generate and open files

### PR DESCRIPTION
**Pull request by hhaidar**
* Runs guard, which  runs rake
* Watches for file changes and rebuilds from middleman
* Opens a browser window on guard startup

```
bundle install
bundle exec guard
```

### CODE REVIEW

**Comment by funkaoshi** [comment]
@hhaidar nice man.

**Comment by emintham** [comment]
Probably don't want an 'open' for each update. We can just refresh the browser window. Also, you can remove my script since yours is a much better approach. The Gemfile.lock shouldn't be in VCS I think?

**Comment by hhaidar** [comment]
@emintham actually `start_end` only fires once, so only one browser window will open for conveniece

Gemfile.lock is in the upstream repo, so we should probably just keep it. I have no idea how gems work though :dancer:

**Comment by emintham** [comment]
I see. gem file specifies the dependencies, Gemfile.lock is autogenerated to contain the actual versions to remove ambiguity. If you git add your Gemfile.lock, upstream repo changes will conflict with it too right?

**Comment by hhaidar** [comment]
@emintham I think it's okay, we can regenerate quite easily.

**Comment by funkaoshi** [comment]
@emintham Gemfile.lock stores the exact versions that were installed when the project was built, and it's what bundler will use to install stuff. So it should be in the repo, and yes, it's confusing.

**Comment by sibartlett** [comment]
I tried it, it worked, I merged it.

**Comment by hhaidar** [comment]
@sibartlett are there any downs sides to this vs running a middleman server?

**Comment by sibartlett** [comment]
The middleman server keeps crashing out for me, so I ended up using the middleman build task. This automates what I was already doing - so good for me.

**Comment by hhaidar** [comment]
@sibartlett oh aight cool, good to know

**Pull request merged**
