### PR TITLE
Add API docs for LDAP connection test endpoints.

### PR DESCRIPTION
**Pull request by RouganStriker**
* Added docs for a bind connection test endpoint
* Added docs for a user authentication test endpoint

### CODE REVIEW

**Comment by funkaoshi** [comment]
Looks good. Seems weird to submit a password like this via the API. I didn't realize the frontend had the password. You'll just return success or an error message, I assume?

**Comment by emintham** [comment]
For the first endpoint are we just checking if the bind succeeds? Maybe do bind as well as a test query (get server info or get bind user's info) then return the corresponding error message to say which stage failed if they did and return 204 if they both work?

**Comment by RouganStriker** [comment]
I was planning on doing just a bind test but doing an additional simple query is an even better idea.

**Comment by emintham** [comment]
+1

**Comment by RouganStriker** [comment]
Updated field descriptions.

**Comment by Gee19** [comment]
+1

**Pull request merged**
