### PR TITLE
Add inaccessible to the param list

### PR DESCRIPTION
**Pull request by harry-kim**
Remove start_tls
Remove some bind_password where its not required

Refs: #SDE-3743

TODO:
- [x] Set milestone label in pull request (SDE version)
- [ ] Updated changelog.md
- [x] Completed documentation for the new endpoint.
- [x] Feature has been merged into SDE develop.

### CODE REVIEW

**Comment by aeldamaty** [comment]
+1

**Comment by funkaoshi** [comment]
Seems fine. Don't forget about the changelog.

**Comment by emintham** [comment]
+1

**Comment by harry-kim** [comment]
updated changelog. merging

**Pull request merged**
