### PR TITLE
Add examples for Reset + Save Project Draft

### PR DESCRIPTION
**Pull request by JeffBain**

### CODE REVIEW

**Comment by sibartlett** [comment]
@JeffBain Is this still valid, and if so can you rebase?

**Comment by JeffBain** [comment]
It should be valid, and I can indeed rebase!

**Comment by sibartlett** [comment]
Also - the docs have been updated to reflect that "settings" has been changed to"survey".

**Comment by JeffBain** [comment]
So it seems like at some point we merged the changes from this in. In light of this, I'm just closing this PR as redundant.

**Pull request closed without merging**
